### ISSUE TITLE
NoMethodError in Raven.capture_exception(exception) 

### ISSUE THREAD

**Issue by chadwtaylor** [getsentry/raven-ruby#418] opened 2015-12-20 14:39 UTC
When I called `Raven.capture_exception(exception)`, it caused a NoMethodError:

```
NoMethodError - undefined method `read_attribute_for_serialization' for #<Raven::Event:0x007fb3812d9128>:
  active_model_serializers (0.9.3) lib/active_model/serializer.rb:88:in `block (2 levels) in attributes'
  active_model_serializers (0.9.3) lib/active_model/serializer.rb:160:in `block in attributes'
  active_model_serializers (0.9.3) lib/active_model/serializer.rb:159:in `attributes'
  active_model_serializers (0.9.3) lib/active_model/serializer.rb:284:in `serializable_object'
  active_model_serializers (0.9.3) lib/active_model/serializable.rb:23:in `block in serializable_object_with_notification'
  activesupport (4.2.3) lib/active_support/notifications.rb:166:in `instrument'
  active_model_serializers (0.9.3) lib/active_model/serializable.rb:55:in `instrument'
  active_model_serializers (0.9.3) lib/active_model/serializable.rb:22:in `serializable_object_with_notification'
  active_model_serializers (0.9.3) lib/active_model/array_serializer.rb:43:in `block in serializable_object'
  active_model_serializers (0.9.3) lib/active_model/array_serializer.rb:42:in `serializable_object'
  active_model_serializers (0.9.3) lib/active_model/serializable.rb:16:in `block in as_json'
  activesupport (4.2.3) lib/active_support/notifications.rb:166:in `instrument'
  active_model_serializers (0.9.3) lib/active_model/serializable.rb:55:in `instrument'
  active_model_serializers (0.9.3) lib/active_model/serializable.rb:10:in `as_json'
  activesupport (4.2.3) lib/active_support/json/encoding.rb:35:in `encode'
  activesupport (4.2.3) lib/active_support/json/encoding.rb:22:in `encode'
  activesupport (4.2.3) lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
  actionpack (4.2.3) lib/action_controller/metal/renderers.rb:116:in `block in <module:Renderers>'
  active_model_serializers (0.9.3) lib/action_controller/serialization.rb:53:in `block (2 levels) in <module:Serialization>'
  actionpack (4.2.3) lib/action_controller/metal/renderers.rb:45:in `block in _render_to_body_with_renderer'
```

**Comment by nateberkopec** [comment] 2015-12-21 16:02
@chadwtaylor Can you provide any additional details here? It looks like you're trying to render a Raven::Event with ActiveModelSerializers? 

Some controller code or other context would be helpful.

**Comment by nateberkopec** [comment] 2016-01-05 19:24
I wonder if this is related to #372

**Comment by nateberkopec** [comment] 2016-03-17 18:51
Closing b/c I'm 99% certain this is #372. Re-open if you've got a reproduction.

**Closed by nateberkopec** 2016-03-17 18:51 UTC
Labels: bug, waiting/blocked
