### ISSUE TITLE
Rack-timeout integration doesn't get loaded

### ISSUE THREAD

**Issue by pawelniewie** [getsentry/raven-ruby#650] opened 2017-03-11 09:30 UTC
rack-timeout 0.4.2, sentry-raven 2.4.0, results with:

`WARN -- sentry: ** [Raven] Unable to load raven/integrations/rack-timeout: An observer with the id :logger is already set.`

That's caused by `require "rack/timeout/base"` in `integrations/rack-timeout.rb` as rack-timeout was already loaded.

**Comment by pawelniewie** [comment] 2017-03-11 09:37
I guess instead of `require "rack/timeout/base"` you should use `require "rack/timeout/core"` or detect if it was loaded before and don't require.

**Comment by nateberkopec** [comment] 2017-03-22 13:17
I can't reproduce this. Do you have an initializer or something else that requires `rack-timeout` somewhere else?

**Comment by nateberkopec** [comment] 2017-05-23 16:30
Closed by ccb049e78

**Closed by nateberkopec** 2017-05-23 16:30 UTC
Labels: bug
