### ISSUE TITLE
Raven::Error - the server responded with status 413

### ISSUE THREAD

**Issue by abarrak** [getsentry/raven-ruby#813] opened 2018-02-08 11:04 UTC
An error report about paperclip upload failures fail with a `413` HTTP code:

```
I, [2018-02-08T09:36:40.409424 #15151]  INFO -- :  Sending event 1ed22cd59f694fa5b9ca109332fb1343 to Sentry
E, [2018-02-08T09:36:41.399689 #15151] ERROR -- : Unable to record event with remote Sentry server (Raven::Error - the server responded with status 413):
/bundle/ruby/2.4.0/gems/sentry-raven-2.7.1/lib/raven/transports/http.rb:34:in `rescue in send_event'
/bundle/ruby/2.4.0/gems/sentry-raven-2.7.1/lib/raven/transports/http.rb:17:in `send_event'
/bundle/ruby/2.4.0/gems/sentry-raven-2.7.1/lib/raven/client.rb:37:in `send_event'
/bundle/ruby/2.4.0/gems/sentry-raven-2.7.1/lib/raven/instance.rb:81:in `send_event'
/bundle/ruby/2.4.0/gems/sentry-raven-2.7.1/lib/raven/instance.rb:126:in `capture_type'
/bundle/ruby/2.4.0/gems/sentry-raven-2.7.1/lib/raven/integrations/rack.rb:28:in `capture_type'
/bundle/ruby/2.4.0/gems/sentry-raven-2.7.1/lib/raven/integrations/rails/overrides/
   debug_exceptions_catcher.rb:8:in `render_exception'
/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_dispatch/middleware/debug_exceptions.rb:69:in `rescue in call'
/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_dispatch/middleware/debug_exceptions.rb:58:in `call'
/bundle/ruby/2.4.0/gems/skylight-1.5.0/lib/skylight/probes/middleware.rb:33:in `call'
/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
```

I think the reason is the lengthy base64 image string that's sent with the exception data.

**Comment by nateberkopec** [comment] 2018-03-20 18:33
Thank you for reporting. Duplicate of #706.

**Closed by nateberkopec** 2018-03-20 18:33 UTC
