### ISSUE TITLE
Request env in rails app is not reported when exceptions occurs in a middleware

### ISSUE THREAD

**Issue by j15e** [getsentry/raven-ruby#250] opened 2014-11-21 18:14 UTC
I got a rack level error in my app and the error reported by raven-ruby has no request detail :

![norequest](https://cloud.githubusercontent.com/assets/143380/5146941/6f74bdc8-717f-11e4-8703-8517d84315d0.png)

Any idea why? I think it should capture some rack env information even if the request is malformed. 

This very specific error does not bother me as it is a human made incorrect HTTP request, but some other rack level error might occur to users and I would like to get all the details about their request.

You can reproduce this kind of error on any rails app with `curl -X XGET http://localhost:3000/`.

**Comment by nateberkopec** [comment] 2015-01-16 00:50
@j15e Sorry it's been so long, but is there any way you could share your middleware stack?

**Comment by j15e** [comment] 2015-01-16 16:29
Hi, yep, here :
```
use Raven::Rack
use Rack::Sendfile
use ActionDispatch::Static
use Rack::Lock
use #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x007f874202bef0>
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use RequestStore::Middleware
use SetAppTenant
use AppLogger
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use ActionDispatch::RemoteIp
use ActionDispatch::Reloader
use ActionDispatch::Callbacks
use ActiveRecord::Migration::CheckPending
use ActiveRecord::ConnectionAdapters::ConnectionManagement
use ActiveRecord::QueryCache
use ActionDispatch::Cookies
use ActionDispatch::Session::ActiveRecordStore
use ActionDispatch::Flash
use ActionDispatch::ParamsParser
use Rack::Head
use RailsWeakEtags::Middleware
use Rack::ConditionalGet
use Rack::ETag
use Warden::Manager
use HttpAcceptLanguage::Middleware
use Bullet::Rack
use OmniAuth::Strategies::Developer
use OmniAuth::Strategies::Bonos
run App::Application.routes
```

**Comment by robertclancy** [comment] 2015-06-03 16:51
Is ShowExceptions enabled? The [wiki](https://github.com/getsentry/raven-ruby/wiki/Integrations#rails) states to disable ShowExceptions.

Since this is an easy thing to miss (as I did), this pr:
https://github.com/getsentry/raven-ruby/pull/343
captures exceptions swallowed by ShowExceptions.

**Comment by seanlinsley** [comment] 2015-09-07 21:13
When reproducing this, I see an error inside Sentry:

<img width="1004" alt="screen shot 2015-09-07 at 4 11 44 pm" src="https://cloud.githubusercontent.com/assets/688886/9722908/53ba3c1c-557b-11e5-87df-cc1762b21964.png">

**Comment by dcramer** [comment] 2015-09-07 21:20
@seanlinsley mind emailing support with a link to that event?

**Comment by seanlinsley** [comment] 2015-09-07 22:32
@dcramer sent

**Comment by dcramer** [comment] 2015-09-07 22:33
@seanlinsley in your case its related to the HTTP verb being used (XGET is invalid). I'm not sure if the right call is to allow arbitrary values or not here.

**Comment by nateberkopec** [comment] 2016-02-23 15:33
So, what's happening here is two things:

1. Our usual "from_rack" exception handling method never gets called because it's inserted into the `ActionDispatch::ShowExceptions` middleware, which is further down the static than `ActionDispatch::Static`, where this occurs. This could theoretically occur anywhere *above* ActionDispatch::ShowExceptions.
2. Sentry's server doesn't like XGET as the HTTP verb, so discards the *entire* request info included. Opened issue https://github.com/getsentry/sentry/issues/2727

**Comment by nateberkopec** [comment] 2016-02-23 15:34
I think point 1 is acceptable, so I'm closing this and moving discussion to the linked Sentry issue. I don't think this is the client's problem, as we're sending all the data we can/should.

**Closed by nateberkopec** 2016-02-23 15:34 UTC
Labels: bug

**Comment by nateberkopec** [comment] 2016-02-25 21:01
This has been fixed upstream.
