### ISSUE TITLE
Call Stack frame introspection

### ISSUE THREAD

**Issue by thedrow** [getsentry/raven-ruby#498] opened 2016-05-03 10:13 UTC
Unlike the Python client the ruby client does not collect information about the state of each frame in the call stack.
As a result, the values of local variables at the time of the exception in each frame are not displayed.
I tried to come up with a way to provide this information and it seems that only the [binding_of_caller](https://github.com/banister/binding_of_caller) gem is able to do so.
However, binding_of_caller should only be used in development and in production according to the README. Both https://github.com/banister/binding_of_caller/issues/59 and https://github.com/banister/binding_of_caller/issues/56 report about performance issues when binding_of_caller is introduced.
Should we add support for stack frame introspection binding_of_caller anyway but keep it disabled by default with a warning that it might cause problems?
An example implementation of Stack frame introspection using binding_of_caller can be found at https://github.com/charliesome/better_errors/blob/master/lib/better_errors/stack_frame.rb#L5

If the answer is no, is there another way to get the information we need in order to collect the frame's state?

**Comment by nateberkopec** [comment] 2016-05-03 12:56
Dupe of #7 - we absolutely can do this, but it's a big project. You've pretty much already mentioned the ways we can capture this data.

**Closed by nateberkopec** 2016-05-03 12:56 UTC
